### ISSUE TITLE
Mover logica de cálculos do frontend para o backend

### ISSUE THREAD

**Issue by jadsonlucio** [jadsonlucio/volpi-water-reminder#1]
Atualmente, o frontend da aplicação executa o cálculo de algumas métricas relacionadas ao consumo de água, que são exibidas ao usuário. Estas métricas incluem o cálculo do total de água consumida e a sua representação em forma de porcentagem, conforme ilustrado na imagem abaixo:

![Imagem da Tela de Consumo](https://github.com/jadsonlucio/volpi-water-reminder/assets/12494137/5774e2e5-5fc1-4932-bc2e-aad1f890c494)

Para aumentar a robustez da aplicação e permitir futuras adaptações na lógica de negócio desses cálculos, é essencial que essa lógica seja transferida do frontend para o backend.

**Mudanças Necessárias:**

**Backend:**
- [x] Atualizar o endpoint responsável por fornecer os valores de consumo ao longo de um período de tempo para incluir estatísticas de consumo durante esse período. #2 
- [x] Atualizar o endpoint utilizado para registrar o consumo diário de forma a incluir estatísticas de consumo na resposta. #4 

**Frontend:**
- [x] Eliminar a lógica de cálculo das estatísticas de consumo da tela de consumo diário. #5 
- [x] Exibir os valores das estatísticas de consumo retornados pelo backend na tela correspondente. #3 

Essas alterações irão desacoplar a lógica de cálculo das métricas de consumo, tornando a aplicação mais flexível e facilitando futuras melhorias na sua lógica de negócio.
